# Generated by Django 5.1 on 2025-02-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_author_post_user_remove_post_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentheart',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
